accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
	url(r'^list/$', views.AccountList.as_view(), name="account_list"),
	url(r'^(?P<uuid>[\w-]+)/$', views.account_detail, name="account_detail"),
	url(r'^new/$', views.account_cru, name='account_new'),
	url(r'^edit/$', views.account_cru, name='account_update'),
]

contacts/urls.py
from django.conf.urls import url

from . import views

app_name = 'contacts'
urlpatterns = [
	url(r'^(?P<uuid>[\w-]+)/$', views.contact_detail, name="contact_detail"),
	url(r'^new/$', views.contact_cru, name="contact_new"),
	url(r'^edit/$', views.contact_cru, name="contact_update"),
	url(r'^(?P<pk>[\w-]+)/delete/$', views.ContactDelete.as_view(), name='contact_delete'),
]

crmapp/urls.py
"""crmapp URL Configuration """
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^marketing/', include('marketing.urls')),
    url(r'^signup/', include('subscribers.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^comm/', include('communications.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

from shortuuidfield import ShortUUIDField


class Account(models.Model):
    uuid = ShortUUIDField(unique=True)
    name = models.CharField(max_length=80)
    desc = models.TextField(blank=True)
    address_one = models.CharField(max_length=100)
    address_two = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    phone = models.CharField(max_length=20)
    owner = models.ForeignKey(User)
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'accounts'

    def __unicode__(self):
        return u"%s" % self.name

    @models.permalink
    def get_absolute_url(self):
        return 'account_detail', [self.uuid]

    @models.permalink
    def get_update_url(self):
        return 'account_update', [self.uuid]

    @models.permalink
    def get_delete_url(self):
        return 'account_delete', [self.uuid]

accounts/forms.py
from django import forms

from .models import Account


class AccountForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = ['name', 'desc', 'address_one', 'address_two',
				'city', 'state', 'phone']
		widgets = {
			'name': forms.TextInput(
				attrs={
					'placeholder': 'Company',
					'class': 'col-md-12 form-control'
				}
			),
			'desc': forms.Textarea(
				attrs={
					'placeholder': 'Enter description',
					'class': 'form-control'
				}
			),
			'address_one': forms.TextInput(
				attrs={
					'placeholder': 'Street Address',
					'class': 'gi-form-addr form-control'
				}
			),
			'address_two': forms.TextInput(
				attrs={
					'placeholder': 'Suite, PO, etc',
					'class': 'gi-form-addr form-control'
				}
			),
			'city': forms.TextInput(
				attrs={
					'placeholder': 'City',
					'class': 'gi-form-addr form-control' 
				}
			),
			'state': forms.TextInput(
				attrs={
					'placeholder': 'State',
					'class': 'gi-form-addr form-control'
				}
			),
			'phone': forms.TextInput(
				attrs={
					'placeholder': 'Phone',
					'class': 'gi-form-addr form-control'
				}
			),
		}

accounts/views.py
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect 
from django.core.urlresolvers import reverse

from communications.models import Communication
from communications.forms import CommunicationForm
from contacts.models import Contact
from .models import Account
from .forms import AccountForm


class AccountList(ListView):
    model = Account
    paginate_by = 12
    template_name = 'accounts/account_list.html'
    context_object_name = 'accounts'

    def get_queryset(self):
        try:
            a = self.request.GET.get('account',)
        except KeyError:
            a = None
        if a:
            account_list = Account.objects.filter(
                name__icontains=a,
                owner=self.request.user
            )
        else:
            account_list = Account.objects.filter(owner=self.request.user)
        return account_list

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AccountList, self).dispatch(*args, **kwargs)


@login_required()
def account_detail(request, uuid):

    account = Account.objects.get(uuid=uuid)
    if account.owner != request.user:
            return HttpResponseForbidden()

    contacts = Contact.objects.filter(account=account)
    communications = Communication.objects.filter(
        account=account).order_by('-created_on')

    form = CommunicationForm()

    variables = {
        'account': account,
        'contacts': contacts,
        'communications': communications,
        'form': form
    }

    return render(request, 'accounts/account_detail.html', variables)


@login_required()
def account_cru(request, uuid=None):

    if uuid:
        account = get_object_or_404(Account, uuid=uuid)
        if account.owner != request.user:
            return HttpResponseForbidden()
        else:
            account = Account(owner=request.user)

    if request.method == 'POST':
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            form.save()
            redirect_url = reverse(
                'crmapp.accounts.views.account_detail',
                args=(account.uuid,)
            )
            return HttpResponseRedirect(redirect_url)
    else:
        form = AccountForm(instance=account)

        variables = {
            'form': form,
            'account': account
        }
        if request.is_ajax():
            template = 'accounts/account_item_form.html'
        else:
            template = 'accounts/account_cru.html'
        
        return render(request, template, variables)

accounts/templates/accounts/account_cru.html
{% extends 'base.html' %}
{% block title %}Account Operation{% endblock title %}

{% block content %}
	<div id="content-container" class="container p-none">
		<div class="side-p">
			{% include 'accounts/account_item_form.html' %}
		</div>
	</div>
{% endblock content %}

accounts/templates/accounts/account_detail.html
{% extends 'base.html' %}

{% block content %}
	<div id="content-container" class="container p-none">
		<div id="ad-container">
			<div id="gi-container" class="ad-container">
				{% include 'accounts/account_item_view.html' %}
			</div>
		</div>
		{# List Contacts #}
		<div id="cd-container" class="ad-container">
    		<div class="ad-headers">
        		<h4 class="ad-mh m-none">Contacts</h4>
    		</div>
    		<div id="cd-body" class="row">
        		<table id="cd-table" class="table table-hover">
            		<tbody>
               			<tr></tr>
               			{% for contact in contacts %}
               				{% include 'contacts/contact_item_view.html' %}
               			{% endfor %}	
               		</tbody>
        		</table>
        		{# New Contact Link #}
       			<a id="new-contact" class="btn btn-link" 
            href="{% url 'contacts:contact_new' %}?account={{ account.id }}">New Contact</a>
    		</div>
		</div>
        {# List Communications #}
        <div id="co-container" class="ad-container">
            <div class="ad-headers">
                <h4 class="ad-mh m-none">Communications</h4>
            </div>
        <div id="co-body" class="ad-container">
            {# Communications Item Form #}
            <div id="co-form-wrapper">
                {% include 'communications/comm_item_form.html' %}
            </div>
            {# List of Communications #}
            <ul id="co-list" class="strip-list col-md-12 p-none">
                {% for comm in communications %}
                    {% include 'communications/comm_item_view.html' %}
                {% endfor %}
            </ul>
        </div>
    </div>
	</div>
{% endblock content %}

accounts/templates/accounts/account_item_form.html
<form id="gi-form" action="{% if account.uuid %}{{ account.get_update_url }}
{% else %}{{ url 'accounts:account_new'}}{% endif %}" method="post"> 
	{% csrf_token %}
	<div id="gi-h-w">
		<h3 class="gi-mh">{{ form.name }}</h3>
		<span>{{ form.name.errors }}</span>
	</div>
	<div class="row">
		<div class="row-md-9">
			<p>{{ form.desc }}</p>
			<span>{{ form.desc.errors }}</span>
		</div>
		<div class="col-md-3">
            <p class="nm">{{ form.address_one }}</p>
            <span>{{ form.address_one.errors }}</span>
            <p class="nm">{{ form.address_two }}</p>
            <span>{{ form.address_one.errors }}</span>
            <p class="nm">{{ form.city}}</p>
            <span>{{ form.city.errors }}</span>
            <p class="nm">{{ form.state }}</p>
            <span>{{ form.state.errors }}</span>
            <p class="nm">{{ form.phone}}</p>
            <span>{{ form.phone.errors }}</span>
        </div>
	</div>
	<input id="gi-form-submit" class="btn btn-primary" type="submit" value="SAVE">
	<p>{{ form.non_field_errors }}</p>
</form>

accounts/templates/accounts/account_item_view.html
<div class="gi-header">
	<h3 class="ad-mh">{{ account.name }}
		{# Account Edit Link #}
        <span>
            <a class="ad-control edit-account btn btn-link"
               href="{{ account.get_update_url }}">Edit</a>
        </span>
	</h3>

</div>
<div class="row gi-body">
	<div class="col-mg-9">
		<h5 class="gi-sh">Description</h5>
		<p>{{{ account.desc }}</p>
	</div>	
	<div class="col-md-3">
		<h5 class="gi-sh">Address</h5>
		<p class="nm">{{ account.address_one }}</p>
		<p class="nm">{{ account.address_two }}</p>
		<p class="nm">{{ account.city }}, {{ account.state }}</p>
		<p class="nm">{{ account.phone }}</p>
	</div>
</div>

accounts/templates/accounts/account_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Account List{% endblock title %}

{% block content %}
	<div id="content-container" class="container p-none">
		<div id="al-container" class="side-p">
			<div id="al-control">
				<h3 class="ad-mh">Account List
					{# Add Account Link #}
					<span class="pull-right">
    					<a href="{% url 'accounts:account_new' %}"
       						class="btn btn-link p-r-none">+ Add New Account</a>
					</span>
				</h3>
				{# Account Search Form #}
				<form action="{% url 'accounts:account_list' %}" method="get">
					<input id="al-search" type="text" name="account" value="{{ request.GET.account }}" class="form-control" />
					<input type="submit" value="Search" class="btn btn-success" />
				</form>	
			</div>
			{# List of Accounts #}
			<ul id="al-group" class="strip-list">
				{% for account in accounts %}
					<li class="al-item">
						<a href="{{ account.get_absolute_url }}"><h4 class="al-name">{{ account.name }}</h4></a>
						<span class="al-created">created on {{ account.created_on }}</span>
					</li>
				{% endfor %}	
			</ul>
			{# Pagination Section #}
			{% if is_paginated %}
    			<div id="al-paginate">
        			<ul class="strip-list al-pgnt-list">
            			{% if page_obj.has_previous %}
                			<li class="pull-left">
                    			<a href="{% url 'accounts:account_list' %}?page={{ page_obj.previous_page_number }}
                    			{% if request.GET.account %}&account={{ request.GET.account }}{% endif %}">Prev</a>
                			</li>
            			{% endif %}
            			{% if page_obj.has_next %}
                			<li class="pull-right">
                    			<a href="{% url 'accounts:account_list' %}?page={{ page_obj.next_page_number }}
                    			{% if request.GET.account %}&account={{ request.GET.account }}{% endif %}">Next</a>
                			</li>
            			{% endif %}
        			</ul>
    			</div>
			{% endif %}
		</div>
	</div>
{% endblock content %}