accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
	url(r'^list/$', views.AccountList.as_view(), name="account_list"),
	url(r'^(?P<uuid>[\w-]+)/$', views.account_detail, name="account_detail"),
	url(r'^new/$', views.account_cru, name='account_new'),
	url(r'^edit/$', views.account_cru, name='account_update'),
]

crmapp/urls.py
"""crmapp URL Configuration """
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^marketing/', include('marketing.urls')),
    url(r'^signup/', include('subscribers.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^comm/', include('communications.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}),
    url(r'^admin/', admin.site.urls),
]

subscribers/urls.py
from django.conf.urls import url

from . import views

app_name = 'subscribers'
urlpatterns = [
	url(r'^$', views.subscriber_new, name='sub_new'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    {# Make modifiable head elements #}
    <head>
        <title>{% block title %}Home {% endblock title %} | CRM Easy</title>
        {% block head_favicon %}
            <link rel="icon" type="image/png"
                  href="{% static 'images/favicon.ico'%}">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
                <link href="{% static 'css/bootstrap.min.css' %}"
                      rel="stylesheet" media="screen">
                <link href="{% static 'css/app.css' %}"
                      rel="stylesheet" media="screen">
            {% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
    </head>
    <body>
        {# Navigation Menu #}
        <header>
            <div class="navbar navbar-default navbar-static-top
            {% block nav-style %}{% endblock %}">
                <div class="container p-none">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle"
                                data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">CRM Easy</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li><a href="/logout/">Logout</a></li>
                                <li><a href="{% url 'accounts:account_list' %}"
                                       class="p-r-none">Accounts</a></li>
                            {% else %}
                                <li><a href="/login/">Login</a></li>
                                <li><a href="{% url 'subscribers:sub_new' %}" class="p-r-none">Sign Up</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        {# The Document Body #}
        <div id="site-wrapper">
            {% block content %}
                if you see this, something is wrong!
            {% endblock content %}
        </div>
        {# The Footer #}
        <div class="footer">
            <div class="container">
                <p>Copyright CRM Easy</p>
            </div>
        </div>
    </body>
    {# Set of blocks that can be used to display JavaScript files #}
    {% block footer_javascript %}
        {% block footer_javascript_site %}
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.is' %}"></script>
            <script src="{% static 'js/app.js' %}"></script>
        {% endblock footer_javascript_site %}
        {% block footer_javascript_section %}{% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post"
                  action="{% url 'login' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username"
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password"
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login"
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}

templates/object_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{ object_name }} Confirm delete?{% endblock title %}

{% block content %}
	<div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link" 
                       type="button" value="Cancel" 
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock content %}